Establishing data

In [2]:
# Boston population data
boston_1850 = 136881
boston_1860 = 177840
boston_1870 = 250526

# New York population data
ny_1850 = 515547
ny_1860 = 813669
ny_1870 = 942292

# Philadelphia population data
phil_1850 = 121376
phil_1860 = 565529
phil_1870 = 674022


Is Boston's pop over 200,000 in 1870

In [4]:
boston_1870 > 200,000

(True, 0)

comparing ny & philly 1860 pops

In [8]:
if ny_1860 > phil_1860:
    print("New York had a larger population than Philadelphia in 1860.")
else:
    print("New York did not have a larger population than Philadelphia in 1860.")

New York had a larger population than Philadelphia in 1860.


seeing if philly's pop more than doubled between 1850 & 1860

In [10]:
if phil_1860 > 2*phil_1850:
    print("Philadelphia's population more than doubled between 1850 and 1860.")
else:
    print("Philadlephia's population did not more than double between 1850 and 1860.")

Philadelphia's population more than doubled between 1850 and 1860.


establishing growth

In [13]:
# Calculate population growth
boston_growth = boston_1870 - boston_1850
ny_growth = ny_1870 - ny_1850
phil_growth = phil_1870 - phil_1850


identify fastest growing city

In [19]:
if boston_growth > ny_growth and phil_growth:
    print("Boston was the fastest growing city!")
elif ny_growth > boston_growth and phil_growth:
    print("New York was the fastest growing city!")
else:
    print("Philadelphia was the fastest growing city!")

New York was the fastest growing city!


boston pop over 200,000 in 1870 and increased by at least 100,000 from 1850 to 1870

In [23]:
boston_1870 > 200,000 and boston_growth > 100,000

(True, 0, 0)

Use or to check if either one of these condition was true in 1860:
New York’s population was over 800,000 in 1860
OR Philadelphia’s population was over 800,000 in 1860

In [26]:
ny_1860 > 800,000 or phil_1860 > 800,000

(True, True, 0)

Create variables for the percent growth (rather than absolute growth) of each city between 1850-1870 - ex. “Philadelphia grew xx% between 1850 and 1870

In [49]:
boston_percent_growth = (boston_growth/boston_1850)*100
ny_percent_growth = (ny_growth/ny_1850)*100
phil_percent_growth = (phil_growth/phil_1850)*100

In [59]:
if boston_percent_growth > 100:
    boston_growth_cat = "High Growth"
else:
    boston_growth_cat = "Low Growth"
print("Boston was a",boston_growth_cat,"city")

Boston was a Low Growth city
